const mongoose = require('mongoose');

const AffiliateSchema = new mongoose.Schema({
  userId:           { type: String, required: true, unique: true },
  code:             { type: String, required: true, unique: true, uppercase: true, minlength: 6, maxlength: 10 },
  tier:             { type: String, enum: ['standard', 'premium', 'partner'], default: 'standard' },

  // Counts
  referralCount:    { type: Number, default: 0 },
  activeReferrals:  { type: Number, default: 0 },  // referred users with ≥1 bet in last 30d

  // Revenue
  totalVolume:      { type: Number, default: 0 },  // total USDC volume generated by referrals
  totalEarned:      { type: Number, default: 0 },  // all-time earned
  pendingPayout:    { type: Number, default: 0 },  // queued for next payout

  lastPayoutAt:     { type: Date, default: null },
  createdAt:        { type: Date, default: Date.now },
});

// Tier payout percentages of platform fees
AffiliateSchema.statics.tierPct = { standard: 0.30, premium: 0.40, partner: 0.50 };

module.exports = mongoose.model('Affiliate', AffiliateSchema);
