const mongoose = require('mongoose');

// ─── State machine ─────────────────────────────────────────────────────────────
const TRANSITIONS = {
  draft:          ['pending_review'],
  pending_review: ['active', 'rejected'],
  active:         ['resolving', 'cancelled'],
  resolving:      ['resolved', 'disputed'],
  resolved:       ['claiming'],
  claiming:       ['closed'],
  // terminal: closed, rejected, cancelled, disputed
};

const MarketSchema = new mongoose.Schema({
  creatorId:      { type: String, required: true, index: true },
  title:          { type: String, required: true },
  description:    String,
  category:       { type: String, enum: ['sport','crypto','politique','culture','autre'], default: 'autre' },
  oracleLevel:    { type: Number, enum: [1,2,3], default: 2 },
  confidenceScore:{ type: Number, default: 0 },
  confidenceDetails: {
    verifiability: Number,
    toxicity:      Number,
    explanation:   String,
  },
  status: {
    type: String,
    // includes old values (pending, frozen) for backward compat with existing DB docs
    enum: ['draft','pending_review','pending','active','resolving','resolved','claiming','closed','rejected','cancelled','disputed','frozen'],
    default: 'pending_review',
    index: true,
  },
  outcome:        { type: String, enum: ['YES','NO', null], default: null },
  totalYes:       { type: Number, default: 0 },
  totalNo:        { type: Number, default: 0 },
  creatorStake:   { type: Number, default: 5 },
  stakeReturned:  { type: Boolean, default: false },
  // ── Creator markets ───────────────────────────────────────────────────────
  creatorMarket:    { type: Boolean, default: false },
  subjectHandle:    String,
  subjectPlatform:  { type: String, enum: ['twitter','tiktok','youtube','instagram'] },
  subjectFollowers: Number,
  communityTag:     String,
  selfMarket:       { type: Boolean, default: false }, // creator = subject → show warning
  resolutionDate: { type: Date, required: true },
  minBet:         { type: Number, default: 1 },
  maxBet:         { type: Number, default: null },
  tags:           { type: [String], default: [] },
  commentsCount:  { type: Number, default: 0 },
  trendingScore:  { type: Number, default: 0, index: true },
  // Moderation
  flagCount:      { type: Number, default: 0 },
  flagReasons:    [{ userId: String, reason: String, createdAt: { type: Date, default: Date.now } }],
  flagged:        { type: Boolean, default: false },
  autoGenerated:  { type: Boolean, default: false }, // true = created by pipeline
  onChainId:      { type: Number, default: null },  // on-chain market ID in BetlyMarket contract
  rejectionReason:String,
  cancelledReason:String,
  // Timestamps
  resolvedAt:     Date,
  cancelledAt:    Date,
  disputedAt:     Date,
  createdAt:      { type: Date, default: Date.now },
}, { timestamps: { createdAt: false, updatedAt: 'updatedAt' } });

// ─── Static transition map ────────────────────────────────────────────────────
MarketSchema.statics.TRANSITIONS = TRANSITIONS;
MarketSchema.statics.ACTIVE_STATUSES = ['active'];
MarketSchema.statics.BETTABLE_STATUSES = ['active'];

// ─── Instance: can this market move to newStatus? ─────────────────────────────
MarketSchema.methods.canTransitionTo = function(newStatus) {
  // Legacy statuses map to nearest equivalent
  const effective = this.status === 'pending' ? 'pending_review' : this.status;
  return (TRANSITIONS[effective] || []).includes(newStatus);
};

// ─── Instance: apply transition with validation ───────────────────────────────
MarketSchema.methods.transitionTo = function(newStatus, meta = {}) {
  if (!this.canTransitionTo(newStatus)) {
    throw new Error(`Invalid transition: ${this.status} → ${newStatus}`);
  }
  this.status = newStatus;
  if (newStatus === 'resolved')  { this.resolvedAt = new Date(); if (meta.outcome) this.outcome = meta.outcome; }
  if (newStatus === 'cancelled') { this.cancelledAt = new Date(); if (meta.reason) this.cancelledReason = meta.reason; }
  if (newStatus === 'disputed')  { this.disputedAt = new Date(); }
  if (newStatus === 'rejected' && meta.reason) this.rejectionReason = meta.reason;
};

module.exports = mongoose.model('Market', MarketSchema);
