/**
 * Module 3 — Auto Publisher
 * Takes validated markets from NATHAN, inserts them into MongoDB,
 * runs moderation, and sends notifications to relevant users.
 */

const Market       = require('../../db/models/Market');
const User         = require('../../db/models/User');
const Notification = require('../../db/models/Notification');
const { analyzeMarket } = require('./moderator');
const logger       = require('../utils/logger');

// System user ID for auto-created markets
let _systemUserId = null;

async function getSystemUserId() {
  if (_systemUserId) return _systemUserId;
  let systemUser = await User.findOne({ username: 'system' }).lean();
  if (!systemUser) {
    systemUser = await User.create({
      username: 'system',
      displayName: 'BETLY System',
      email: 'system@betly.gg',
      authProvider: 'email',
    });
    logger.info('autoPublisher: created system user');
  }
  _systemUserId = systemUser._id.toString();
  return _systemUserId;
}

function generateSlug(title) {
  return title
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')  // remove accents
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 80)
    .replace(/-$/, '');
}

/**
 * Publish a single generated market
 * @param {Object} generatedMarket — from marketGenerator
 * @returns {Object|null} — saved Market document or null if rejected
 */
async function publishMarket(generatedMarket) {
  const creatorId = await getSystemUserId();

  // Run through moderator (same as user-created markets)
  const modResult = await analyzeMarket(
    generatedMarket.title,
    generatedMarket.description
  );

  if (modResult.decision === 'rejected') {
    logger.info(`autoPublisher: rejected "${generatedMarket.title}" — ${modResult.rejectionReason}`);
    return null;
  }

  const resolutionDate = new Date(
    Date.now() + (generatedMarket.resolutionDays || 30) * 24 * 60 * 60 * 1000
  );

  const market = new Market({
    creatorId,
    title: generatedMarket.title,
    description: generatedMarket.description,
    category: modResult.category || generatedMarket.category || 'autre',
    oracleLevel: modResult.oracleLevel || generatedMarket.oracleLevel || 2,
    confidenceScore: modResult.confidenceScore || generatedMarket.confidence || 70,
    confidenceDetails: {
      verifiability: modResult.verifiability,
      toxicity: modResult.toxicity,
      explanation: modResult.confidenceExplanation,
    },
    status: modResult.decision === 'approved' ? 'active' : 'pending_review',
    resolutionDate,
    tags: generatedMarket.tags || [],
    // Mark as auto-generated
    autoGenerated: true,
  });

  await market.save();
  logger.info(`autoPublisher: published "${market.title}" (id: ${market._id}, status: ${market.status})`);

  // Send notifications to interested users
  await notifyUsers(market);

  return market;
}

/**
 * Notify users who might be interested in this market
 */
async function notifyUsers(market) {
  try {
    // Find users who have bet on markets in the same category recently
    const Bet = require('../../db/models/Bet');
    const h48 = new Date(Date.now() - 48 * 60 * 60 * 1000);

    const recentBettors = await Bet.aggregate([
      { $match: { placedAt: { $gte: h48 } } },
      {
        $lookup: {
          from: 'markets',
          localField: 'marketId',
          foreignField: '_id',
          as: 'market',
        },
      },
      { $unwind: '$market' },
      { $match: { 'market.category': market.category } },
      { $group: { _id: '$userId' } },
      { $limit: 100 }, // cap notifications per market
    ]);

    if (recentBettors.length === 0) return;

    const notifications = recentBettors.map(b => ({
      userId: b._id,
      type: 'market_approved',
      message: `Nouveau marché ${market.category} : "${market.title.slice(0, 60)}"`,
      marketId: market._id.toString(),
    }));

    await Notification.insertMany(notifications);
    logger.info(`autoPublisher: notified ${notifications.length} users for market ${market._id}`);
  } catch (err) {
    // Non-critical — don't fail the publish
    logger.warn(`autoPublisher: notification error — ${err.message}`);
  }
}

/**
 * Publish a batch of generated markets
 * @param {Array} generatedMarkets — from marketGenerator
 * @returns {Array} — successfully published Market documents
 */
async function publishAll(generatedMarkets) {
  const published = [];

  for (const gm of generatedMarkets) {
    try {
      const market = await publishMarket(gm);
      if (market) published.push(market);
    } catch (err) {
      logger.warn(`autoPublisher: failed to publish "${gm.title?.slice(0, 50)}" — ${err.message}`);
    }
  }

  logger.info(`autoPublisher: published ${published.length}/${generatedMarkets.length} markets`);
  return published;
}

module.exports = { publishAll, publishMarket };
