const https = require('https');
const logger = require('winston');
const Market = require('../../db/models/Market');
const User = require('../../db/models/User');
const { createPool } = require('../lib/cpmm');

const GAMMA_API = 'https://gamma-api.polymarket.com/markets';

function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'Betly/1.0' } }, (res) => {
      let data = '';
      res.on('data', d => data += d);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(e); }
      });
    }).on('error', reject);
  });
}

// Map Polymarket tags/title to Betly categories
function mapCategory(title, tags) {
  const t = (title + ' ' + (tags || []).join(' ')).toLowerCase();
  if (/bitcoin|btc|eth|crypto|solana|xrp|token|defi/i.test(t)) return 'crypto';
  if (/nba|nfl|football|soccer|tennis|match|league|win.*fc|fc.*win|goals|score|playoff/i.test(t)) return 'sport';
  if (/trump|biden|election|president|congress|senate|vote|political|party/i.test(t)) return 'politique';
  if (/album|movie|music|show|celebrity|rihanna|drake|oscar|grammy/i.test(t)) return 'culture';
  if (/temperature|weather|elon|tweet|space|ai|tech|google|apple/i.test(t)) return 'autre';
  return 'autre';
}

/**
 * Sync markets from Polymarket Gamma API.
 * @param {Object} opts
 * @param {number} opts.limit - max markets to fetch
 * @param {number} opts.maxDaysAhead - only import markets ending within N days
 * @param {number} opts.minVolume - minimum volume to import
 */
async function syncPolymarketMarkets(opts = {}) {
  const { limit = 50, maxDaysAhead = 30, minVolume = 50 } = opts;

  const endMax = new Date(Date.now() + maxDaysAhead * 24 * 60 * 60 * 1000).toISOString();
  const url = `${GAMMA_API}?active=true&closed=false&limit=${limit}&order=volume&ascending=false&end_date_max=${endMax}`;

  let markets;
  try {
    markets = await fetchJSON(url);
  } catch (err) {
    logger.error(`[Syncer] Gamma API error: ${err.message}`);
    return { imported: 0, skipped: 0, errors: 0 };
  }

  if (!Array.isArray(markets)) {
    logger.warn('[Syncer] Unexpected Gamma response');
    return { imported: 0, skipped: 0, errors: 0 };
  }

  // Get system user
  let systemUser = await User.findOne({ username: 'system' });
  if (!systemUser) {
    systemUser = await User.create({ username: 'system', telegramId: 'system', balance: 0 });
  }
  const systemId = systemUser.telegramId || systemUser._id.toString();

  let imported = 0, skipped = 0, errors = 0;

  for (const m of markets) {
    try {
      // Skip non-binary
      const outcomes = typeof m.outcomes === 'string' ? JSON.parse(m.outcomes) : m.outcomes;
      if (!outcomes || outcomes.length !== 2) { skipped++; continue; }

      // Skip low volume
      if ((m.volume || 0) < minVolume) { skipped++; continue; }

      // Skip already imported (dedup by conditionId)
      if (!m.conditionId) { skipped++; continue; }
      const existing = await Market.findOne({ polymarketConditionId: m.conditionId });
      if (existing) { skipped++; continue; }

      // Parse odds
      const prices = typeof m.outcomePrices === 'string' ? JSON.parse(m.outcomePrices) : m.outcomePrices;
      const yesPrice = parseFloat(prices?.[0] || '0.5');

      // Token IDs
      const tokenIds = typeof m.clobTokenIds === 'string' ? JSON.parse(m.clobTokenIds) : m.clobTokenIds;
      const tokenYes = tokenIds?.[0] || null;

      // Create CPMM pool seeded at Polymarket odds
      const pool = createPool(40, yesPrice);

      const market = new Market({
        creatorId: systemId,
        title: m.question || m.title || 'Untitled',
        description: m.description || '',
        category: mapCategory(m.question || m.title || '', m.tags),
        oracleLevel: 0,
        status: 'active',
        resolutionDate: new Date(m.endDate),
        autoGenerated: true,
        confidenceScore: 100,
        source: 'polymarket',
        polymarketConditionId: m.conditionId,
        polymarketTokenId: tokenYes,
        polymarketSlug: m.slug || null,
        polymarketEndDate: new Date(m.endDate),
        poolYes: pool.poolYes,
        poolNo: pool.poolNo,
        poolK: pool.poolK,
      });

      await market.save();
      imported++;
      logger.info(`[Syncer] Imported: ${market.title.slice(0, 60)} | ${(yesPrice * 100).toFixed(0)}% YES | ends ${m.endDate?.slice(0, 10)}`);
    } catch (err) {
      errors++;
      logger.error(`[Syncer] Error importing ${m.question?.slice(0, 40)}: ${err.message}`);
    }
  }

  logger.info(`[Syncer] Done: ${imported} imported, ${skipped} skipped, ${errors} errors`);
  return { imported, skipped, errors };
}

/**
 * Check Polymarket for resolved markets and auto-resolve on Betly.
 */
async function resolvePolymarketMarkets() {
  const markets = await Market.find({
    source: 'polymarket',
    oracleLevel: 0,
    status: { $in: ['active', 'resolving'] },
    polymarketConditionId: { $ne: null },
  });

  if (markets.length === 0) return { resolved: 0 };

  let resolved = 0;

  for (const market of markets) {
    try {
      const url = `${GAMMA_API}?condition_id=${market.polymarketConditionId}`;
      const results = await fetchJSON(url);
      const pm = results?.[0];

      if (!pm) continue;

      // Check if resolved
      if (pm.resolved || pm.closed) {
        const prices = typeof pm.outcomePrices === 'string' ? JSON.parse(pm.outcomePrices) : pm.outcomePrices;
        const yesPrice = parseFloat(prices?.[0] || '0');
        const noPrice = parseFloat(prices?.[1] || '0');

        let outcome = null;
        if (yesPrice >= 0.95) outcome = 'YES';
        else if (noPrice >= 0.95) outcome = 'NO';
        else if (pm.outcome === 'Yes' || pm.outcome === 'YES') outcome = 'YES';
        else if (pm.outcome === 'No' || pm.outcome === 'NO') outcome = 'NO';

        if (outcome) {
          // Import the resolver's distributePayout
          const { distributePayout } = require('./resolver');

          market.status = 'resolved';
          market.outcome = outcome;
          market.resolvedAt = new Date();
          await market.save();

          await distributePayout(market, outcome);
          resolved++;
          logger.info(`[Syncer] RESOLVED: ${market.title.slice(0, 50)} → ${outcome}`);
        }
      }
    } catch (err) {
      logger.error(`[Syncer] Resolution check error for ${market._id}: ${err.message}`);
    }
  }

  return { resolved };
}

function startSyncer() {
  // Initial sync after 10s
  setTimeout(async () => {
    await syncPolymarketMarkets({ limit: 30, maxDaysAhead: 7, minVolume: 50 });
  }, 10_000);

  // Sync every 10 minutes
  setInterval(async () => {
    await syncPolymarketMarkets({ limit: 30, maxDaysAhead: 7, minVolume: 50 });
  }, 10 * 60_000);

  // Resolution check every 5 minutes
  setInterval(async () => {
    await resolvePolymarketMarkets();
  }, 5 * 60_000);
}

module.exports = { syncPolymarketMarkets, resolvePolymarketMarkets, startSyncer };
